{
 "title": "App Metrics",
 "description": "Dashboard for visualising metrics collected with the .NET Core library for monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(app)" } },
   { "name": "env", "query": { "query": "label_values(env)" } },
   { "name": "inst", "query": { "query": "label_values(inst)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"$app\",env=\"$env\",inst=~\"$inst\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\",le=\"0.256\",code!~\"101|5.*\"}[$__rate_interval]))\n+\n  sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\",le=\"1.024\",code!~\"101|5.*\"}[$__rate_interval]))\n) / 2 /\n  sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\",le=\"+Inf\",code!~\"101\"}[$__rate_interval]))",
     "legendFormat": "Apdex"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "p95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\",code=~\"2.*|3.*|4.*\"}[$__rate_interval])) /\nsum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\",code=~\"2.*|3.*|4.*|5.*\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\",env=\"$env\",inst=~\"$inst\"} | json | level=~\"warning\" [$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\",env=\"$env\",inst=~\"$inst\"} | json | level=~\"error\" [$__range]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_queue_length_sum{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "In queue"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Total bytes"
    }
   ]
  },
  {
   "title": "GC Paused Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_pause_ratio{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "% Paused Time for GC"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_exceptions_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Criticals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\",env=\"$env\",inst=~\"$inst\"} | json | level=~\"critical\" [$__range]))"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Apdex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\",le=\"0.256\",code!~\"101|5.*\"}[$__rate_interval]))\n+\n  sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\",le=\"1.024\",code!~\"101|5.*\"}[$__rate_interval]))\n) / 2 /\n  sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\",le=\"+Inf\",code!~\"101\"}[$__rate_interval]))",
     "legendFormat": "Apdex"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\nsum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\",code=~\"2.*|3.*|4.*\"}[$__rate_interval])) /\nsum(rate(http_requests_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\",code=~\"2.*|3.*|4.*|5.*\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Request In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Request In Progress"
    }
   ]
  },
  {
   "title": "Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Duration Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "CPU / Thread Pool / Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_num_threads{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(dotnet_threadpool_num_threads{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Pool Threads"
    },
    {
     "expr": "sum(dotnet_threadpool_timer_count{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Timers"
    }
   ]
  },
  {
   "title": "Thread Pool Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_throughput_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(increase(dotnet_threadpool_queue_length_sum{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "In queue"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\",env=\"$env\",inst=~\"$inst\"} | json | level=~\"warning|error|critical\" [$__interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Total bytes"
    },
    {
     "expr": "sum(dotnet_gc_memory_total_available_bytes{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "Total bytes available"
    },
    {
     "expr": "sum(process_working_set_bytes{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "# bytes in physical memory"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_heap_size_bytes{app=\"$app\",env=\"$env\",inst=~\"$inst\"}) by (gc_generation)",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_count_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval])) by (gc_generation)",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC Paused Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_pause_ratio{app=\"$app\",env=\"$env\",inst=~\"$inst\"})",
     "legendFormat": "% Paused Time for GC"
    }
   ]
  },
  { "title": "Exceptions / Locks / JIT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_exceptions_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Locks Contended",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_contention_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Locks Contended"
    }
   ]
  },
  {
   "title": "JIT Compiled Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_jit_method_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "JIT Compiled Methods"
    }
   ]
  },
  {
   "title": "JIT Compiled IL Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_jit_il_bytes{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "JIT Compiled IL Bytes"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_sockets_bytes_sent_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(increase(dotnet_sockets_bytes_received_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_sockets_connections_established_incoming_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(increase(dotnet_sockets_connections_established_outgoing_total{app=\"$app\",env=\"$env\",inst=~\"$inst\"}[$__rate_interval]))",
     "legendFormat": "Outgoing"
    }
   ]
  }
 ]
}