{
 "title": "Prometheus & Loki Count",
 "description": "Dashboard for health-checking all apps connected by the .NET Core library for monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} | {{instance}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - process_start_time_seconds) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\".+\"} | json | level=~\"warning\" [$__range])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\".+\"} | json | level=~\"error\" [$__range])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Criticals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\".+\"} | json | level=~\"critical\" [$__range])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  { "title": "CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (app,env,inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes) by (app,env,inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_queue_length_sum[$__rate_interval])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "GC Paused Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_pause_ratio) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dotnet_exceptions_total[$__rate_interval])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Apdex",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.256\",code!~\"101|5.*\"}[$__rate_interval])) by (app, env, inst)\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1.024\",code!~\"101|5.*\"}[$__rate_interval])) by (app, env, inst)\n) / 2 /\n  sum(rate(http_request_duration_seconds_bucket{le=\"+Inf\",code!~\"101\"}[$__rate_interval])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total[$__rate_interval])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, app, env, inst))",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(rate(http_requests_received_total{code=~\"2.*|3.*|4.*\"}[$__rate_interval])) by (app, env, inst) /\nsum(rate(http_requests_received_total{code=~\"2.*|3.*|4.*|5.*\"}[$__rate_interval])) by (app, env, inst)",
     "legendFormat": "{{env}} | {{app}} | {{inst}}"
    }
   ]
  }
 ]
}