global:
  scrape_interval: 10s # 10 saniyede bir veri çeker

scrape_configs:
  # OpenTelemetry Metrics
  - job_name: 'observability-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['observability-api:8080']

  # Loki Logs Monitoring
  - job_name: 'loki'
    static_configs:
      - targets: ['observability-loki:3100']

  # Tempo Tracing Monitoring
  - job_name: 'tempo'
    static_configs:
      - targets: ['observability-tempo:3200']