auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /var/lib/loki  # ✅ Compactor için gerekli dizin

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb  # ✅ `boltdb-shipper` yerine `tsdb`
      object_store: filesystem
      schema: v13  # ✅ v11 yerine v13
      index:
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /var/lib/loki/tsdb-index
    cache_location: /var/lib/loki/tsdb-cache

limits_config:
  max_query_parallelism: 4
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true  # ✅ v13 schema için gerekli